create or replace PROCEDURE                       EDSP_SEG_SOLICITUD_CONSULTAR (
P_VNRO_SOLICITUD VARCHAR2,
P_VDNI VARCHAR2,
P_VFECHA_INI VARCHAR2,
P_VFECHA_FIN VARCHAR2,
P_NPAGE NUMBER,
P_NSIZE NUMBER,
P_CRESULT OUT SYS_REFCURSOR,
P_CRTOTAL OUT SYS_REFCURSOR 
)
AS
BEGIN

OPEN P_CRTOTAL FOR 
SELECT COUNT(1) TOTAL FROM (
SELECT 
SOL.ID_SOLICITUD,
SOL.ID_TIPO_REGISTRO,
FE_FECHA_SOLICITUD,
CO_ESTADO_SOLICITUD,
NU_SOLICITUD_NUMERO,
TRG.DE_DESCRIPCION DE_DESCRIPCION_TIPO_REG,
SES.DE_DESCRIPCION DE_DESCRIPCION_SOL_ESTADO,
ARS.CO_NOMBRE CO_NOMBRE_ARCH_SUSTENTO,
ARR.CO_NOMBRE CO_NOMBRE_ARCH_RESPUESTA
FROM IDO_PLATAFORMA_EXPE.EDTC_SOLICITUD SOL
INNER JOIN IDO_PLATAFORMA_EXPE.EDTM_SOL_TIPO_REGISTRO TRG ON SOL.ID_TIPO_REGISTRO = TRG.ID_TIPO_REGISTRO
INNER JOIN IDO_PLATAFORMA_EXPE.EDTM_SOL_ESTADO SES ON SOL.CO_ESTADO_SOLICITUD = SES.ID_SOL_ESTADO
LEFT JOIN IDO_PLATAFORMA_EXPE.EDTR_ARCHIVO ARS ON SOL.ID_ARCHIVO_SUSTENTO = ARS.ID_ARCHIVO
LEFT JOIN IDO_PLATAFORMA_EXPE.EDTR_ARCHIVO ARR ON SOL.ID_ARCHIVO_RESPUESTA = ARR.ID_ARCHIVO
WHERE NU_DOC_IDENTIDAD_SOLICITANTE = P_VDNI 
AND (P_VNRO_SOLICITUD IS NULL OR NU_SOLICITUD_NUMERO = P_VNRO_SOLICITUD) 
AND (P_VFECHA_INI IS NULL OR TO_CHAR(FE_FECHA_SOLICITUD, 'YYYY-MM-DD') >= P_VFECHA_INI)
AND (P_VFECHA_FIN IS NULL OR TO_CHAR(FE_FECHA_SOLICITUD, 'YYYY-MM-DD') <= P_VFECHA_FIN)
UNION
SELECT 
SOL.ID_SOLICITUD,
SOL.ID_TIPO_REGISTRO,
FE_FECHA_SOLICITUD,
CO_ESTADO_SOLICITUD,
NU_SOLICITUD_NUMERO,
TRG.DE_DESCRIPCION DE_DESCRIPCION_TIPO_REG,
SES.DE_DESCRIPCION DE_DESCRIPCION_SOL_ESTADO,
ARS.CO_NOMBRE CO_NOMBRE_ARCH_SUSTENTO,
ARR.CO_NOMBRE CO_NOMBRE_ARCH_RESPUESTA
FROM IDO_PLATAFORMA_EXPE.EDTC_SOLICITUD SOL
INNER JOIN IDO_PLATAFORMA_EXPE.EDTD_DET_SOL_FIRMA DET ON SOL.ID_SOLICITUD = DET.ID_SOLICITUD 
INNER JOIN IDO_PLATAFORMA_EXPE.EDTM_SOL_TIPO_REGISTRO TRG ON SOL.ID_TIPO_REGISTRO = TRG.ID_TIPO_REGISTRO
INNER JOIN IDO_PLATAFORMA_EXPE.EDTM_SOL_ESTADO SES ON SOL.CO_ESTADO_SOLICITUD = SES.ID_SOL_ESTADO
LEFT JOIN IDO_PLATAFORMA_EXPE.EDTR_ARCHIVO ARS ON SOL.ID_ARCHIVO_SUSTENTO = ARS.ID_ARCHIVO
LEFT JOIN IDO_PLATAFORMA_EXPE.EDTR_ARCHIVO ARR ON SOL.ID_ARCHIVO_RESPUESTA = ARR.ID_ARCHIVO 
WHERE DET.NU_DOC_IDENTIDAD = P_VDNI
AND (P_VNRO_SOLICITUD IS NULL OR NU_SOLICITUD_NUMERO = P_VNRO_SOLICITUD)  
AND (P_VFECHA_INI IS NULL OR TO_CHAR(FE_FECHA_SOLICITUD, 'YYYY-MM-DD') >= P_VFECHA_INI)
AND (P_VFECHA_FIN IS NULL OR TO_CHAR(FE_FECHA_SOLICITUD, 'YYYY-MM-DD') <= P_VFECHA_FIN)
) T01;

OPEN P_CRESULT FOR 
SELECT * FROM (
SELECT 
ROW_NUMBER() OVER(ORDER BY NU_SOLICITUD_NUMERO) ROW_ID,
ID_SOLICITUD,
ID_TIPO_REGISTRO,
FE_FECHA_SOLICITUD,
CO_ESTADO_SOLICITUD,
NU_SOLICITUD_NUMERO,
DE_DESCRIPCION_TIPO_REG,
DE_DESCRIPCION_SOL_ESTADO,
CO_NOMBRE_ARCH_SUSTENTO,
CO_NOMBRE_ARCH_RESPUESTA
FROM (
SELECT 
SOL.ID_SOLICITUD,
SOL.ID_TIPO_REGISTRO,
FE_FECHA_SOLICITUD,
CO_ESTADO_SOLICITUD,
NU_SOLICITUD_NUMERO,
TRG.DE_DESCRIPCION DE_DESCRIPCION_TIPO_REG,
SES.DE_DESCRIPCION DE_DESCRIPCION_SOL_ESTADO,
ARS.CO_NOMBRE CO_NOMBRE_ARCH_SUSTENTO,
ARR.CO_NOMBRE CO_NOMBRE_ARCH_RESPUESTA
FROM IDO_PLATAFORMA_EXPE.EDTC_SOLICITUD SOL
INNER JOIN IDO_PLATAFORMA_EXPE.EDTM_SOL_TIPO_REGISTRO TRG ON SOL.ID_TIPO_REGISTRO = TRG.ID_TIPO_REGISTRO
INNER JOIN IDO_PLATAFORMA_EXPE.EDTM_SOL_ESTADO SES ON SOL.CO_ESTADO_SOLICITUD = SES.ID_SOL_ESTADO
LEFT JOIN IDO_PLATAFORMA_EXPE.EDTR_ARCHIVO ARS ON SOL.ID_ARCHIVO_SUSTENTO = ARS.ID_ARCHIVO
LEFT JOIN IDO_PLATAFORMA_EXPE.EDTR_ARCHIVO ARR ON SOL.ID_ARCHIVO_RESPUESTA = ARR.ID_ARCHIVO
WHERE NU_DOC_IDENTIDAD_SOLICITANTE = P_VDNI 
AND (P_VNRO_SOLICITUD IS NULL OR NU_SOLICITUD_NUMERO = P_VNRO_SOLICITUD) 
AND (P_VFECHA_INI IS NULL OR TO_CHAR(FE_FECHA_SOLICITUD, 'YYYY-MM-DD') >= P_VFECHA_INI)
AND (P_VFECHA_FIN IS NULL OR TO_CHAR(FE_FECHA_SOLICITUD, 'YYYY-MM-DD') <= P_VFECHA_FIN)
UNION
SELECT 
SOL.ID_SOLICITUD,
SOL.ID_TIPO_REGISTRO,
FE_FECHA_SOLICITUD,
CO_ESTADO_SOLICITUD,
NU_SOLICITUD_NUMERO,
TRG.DE_DESCRIPCION DE_DESCRIPCION_TIPO_REG,
SES.DE_DESCRIPCION DE_DESCRIPCION_SOL_ESTADO,
ARS.CO_NOMBRE CO_NOMBRE_ARCH_SUSTENTO,
ARR.CO_NOMBRE CO_NOMBRE_ARCH_RESPUESTA
FROM IDO_PLATAFORMA_EXPE.EDTC_SOLICITUD SOL
INNER JOIN IDO_PLATAFORMA_EXPE.EDTD_DET_SOL_FIRMA DET ON SOL.ID_SOLICITUD = DET.ID_SOLICITUD 
INNER JOIN IDO_PLATAFORMA_EXPE.EDTM_SOL_TIPO_REGISTRO TRG ON SOL.ID_TIPO_REGISTRO = TRG.ID_TIPO_REGISTRO
INNER JOIN IDO_PLATAFORMA_EXPE.EDTM_SOL_ESTADO SES ON SOL.CO_ESTADO_SOLICITUD = SES.ID_SOL_ESTADO
LEFT JOIN IDO_PLATAFORMA_EXPE.EDTR_ARCHIVO ARS ON SOL.ID_ARCHIVO_SUSTENTO = ARS.ID_ARCHIVO
LEFT JOIN IDO_PLATAFORMA_EXPE.EDTR_ARCHIVO ARR ON SOL.ID_ARCHIVO_RESPUESTA = ARR.ID_ARCHIVO 
WHERE DET.NU_DOC_IDENTIDAD = P_VDNI
AND (P_VNRO_SOLICITUD IS NULL OR NU_SOLICITUD_NUMERO = P_VNRO_SOLICITUD)  
AND (P_VFECHA_INI IS NULL OR TO_CHAR(FE_FECHA_SOLICITUD, 'YYYY-MM-DD') >= P_VFECHA_INI)
AND (P_VFECHA_FIN IS NULL OR TO_CHAR(FE_FECHA_SOLICITUD, 'YYYY-MM-DD') <= P_VFECHA_FIN)
)T02 
)T03 WHERE T03.ROW_ID > P_NPAGE*P_NSIZE AND T03.ROW_ID <= (P_NPAGE+1)*P_NSIZE;
END;