create or replace PROCEDURE EDSP_DET_FIRMA_ARCHIVO_OBTENER (
P_VID_DET_FIRMA VARCHAR2,
P_CRRESULT OUT SYS_REFCURSOR
)
AS

BEGIN
    OPEN P_CRRESULT FOR
    SELECT DAF.ID_ADJ_SOL_FIRMA,
    DAF.ID_DET_SOL_FIRMA,
    DAF.ID_ARCHIVO,
    DAF.CO_TIPO_ARCHIVO,
    ARC.CO_NOMBRE, 
    ARC.DE_NOMBRE_ORIGINAL, 
    ARC.CO_EXTENSION,
    TAR.DE_NOMBRE_ARCHIVO,
    DAF.CO_USO_ARCHIVO
    FROM IDO_PLATAFORMA_EXPE.EDTD_DET_ARCH_SOL_FIRMA DAF
    INNER JOIN IDO_PLATAFORMA_EXPE.EDTR_ARCHIVO ARC ON DAF.ID_ARCHIVO = ARC.ID_ARCHIVO
    INNER JOIN IDO_PLATAFORMA_EXPE.EDTV_TIPO_ARCHIVO TAR ON DAF.CO_TIPO_ARCHIVO = TAR.ID_TIPO_ARCHIVO
    WHERE DAF.CO_ESTADO = '1' AND DAF.ID_DET_SOL_FIRMA = P_VID_DET_FIRMA;

END;