create or replace procedure  EDSP_REGCIV_REGISTRAR (
p_AP_SEGUNDO_APELLIDO VARCHAR2
,p_NU_CELULAR VARCHAR2 
,p_ID_CREA VARCHAR2
,p_ID_TIPO_SOLICITUD_FIRMA VARCHAR2
,p_CO_OREC_REG_CIVIL VARCHAR2
,p_CO_ESTADO_REGISTRADOR VARCHAR2
,p_DE_MAIL VARCHAR2 
,p_AP_PRIMER_APELLIDO VARCHAR2
,p_FE_CAMBIO_ESTADO DATE
,p_DE_DETALLE_OREC_CORTA VARCHAR2
,p_NO_PRENOMBRES VARCHAR2
,p_CO_TIPO_DOC_IDENTIDAD VARCHAR2
,p_NU_DOC_IDENTIDAD VARCHAR2 
) AS
    begin
    insert into EDTM_REG_CIVIL(
    ID_REG_CIVIL,
    AP_SEGUNDO_APELLIDO
    ,NU_CELULAR
    ,ID_CREA  
    ,FE_CREA
    ,ID_TIPO_SOLICITUD_FIRMA    
    ,CO_OREC_REG_CIVIL
    ,CO_ESTADO_REGISTRADOR
    ,DE_MAIL
    ,AP_PRIMER_APELLIDO  
    ,FE_CAMBIO_ESTADO
    ,DE_DETALLE_OREC_CORTA
    ,NO_PRENOMBRES   
    ,CO_TIPO_DOC_IDENTIDAD
    ,NU_DOC_IDENTIDAD
    ) 
    values (
    IDO_PLATAFORMA_EXPE.EDSE_MREG_CIVIL.nextval,
    p_AP_SEGUNDO_APELLIDO
    ,p_NU_CELULAR
    ,p_ID_CREA
    ,SYSDATE
    ,p_ID_TIPO_SOLICITUD_FIRMA   
    ,p_CO_OREC_REG_CIVIL
    ,p_CO_ESTADO_REGISTRADOR
    ,p_DE_MAIL
    ,p_AP_PRIMER_APELLIDO   
    ,p_FE_CAMBIO_ESTADO
    ,p_DE_DETALLE_OREC_CORTA
    ,p_NO_PRENOMBRES    
    ,p_CO_TIPO_DOC_IDENTIDAD
    ,p_NU_DOC_IDENTIDAD
    );
end;