create or replace PROCEDURE EDSP_SOL_DET_FIRMA_OBTENER (
P_VID_SOL VARCHAR2,
P_CRRESULT OUT SYS_REFCURSOR
)
AS

BEGIN
    OPEN P_CRRESULT FOR
    SELECT DTF.ID_DET_SOL_FIRMA,
    DTF.ID_SOLICITUD,
    DTF.ID_TIPO_SOLICITUD_FIRMA,
    DTF.CO_TIPO_DOC_IDENTIDAD,
    DTF.NU_DOC_IDENTIDAD,
    DTF.AP_PRIMER_APELLIDO,
    DTF.AP_SEGUNDO_APELLIDO,
    DTF.NO_PRENOMBRES,
    DTF.NU_CELULAR,
    DTF.CO_ESTADO,DTF.DE_EMAIL,
    TSF.DE_DESCRIPCION DE_DESCRIPCION_TIPO_SOL,
    DTF.CO_ESTADO_FIRMA
    FROM IDO_PLATAFORMA_EXPE.EDTD_DET_SOL_FIRMA DTF 
    INNER JOIN IDO_PLATAFORMA_EXPE.EDTM_TIPO_SOLICITUD_FIRMA TSF ON DTF.ID_TIPO_SOLICITUD_FIRMA = TSF.ID_TIPO_SOLICITUD_FIRMA
    WHERE DTF.CO_ESTADO = '1' AND DTF.ID_SOLICITUD = P_VID_SOL;

END;