create or replace procedure EDSP_REGCIV_ACT_BAJA (
p_CO_ESTADO_REGISTRADOR VARCHAR2 
,p_FE_CAMBIO_ESTADO DATE 
,p_CO_TIPO_DOC_IDENTIDAD VARCHAR2
,p_NU_DOC_IDENTIDAD VARCHAR2 
,p_ID_ACTUALIZA VARCHAR2 
) is
    begin
    update EDTM_REG_CIVIL
    SET        
    CO_ESTADO_REGISTRADOR = p_CO_ESTADO_REGISTRADOR   
    ,FE_CAMBIO_ESTADO  = p_FE_CAMBIO_ESTADO 
    ,ID_ACTUALIZA = p_ID_ACTUALIZA
    ,FE_ACTUALIZA = SYSDATE
    WHERE CO_TIPO_DOC_IDENTIDAD = p_CO_TIPO_DOC_IDENTIDAD
    AND NU_DOC_IDENTIDAD = p_NU_DOC_IDENTIDAD;    

end;