create or replace PROCEDURE EDSP_UBIGEO_LISTAR (
P_VCOD_UBIGEO VARCHAR2,
P_CRRESULT OUT SYS_REFCURSOR
)
AS
VCOD_LEN NUMBER := 0;
VCOD_DEP VARCHAR2(2) := '';
VCOD_PRO VARCHAR2(2) := '';
VCOD_DIST VARCHAR2(2) :='';

BEGIN
    VCOD_LEN := LENGTH(P_VCOD_UBIGEO);
     
    IF VCOD_LEN IS NULL THEN

        OPEN P_CRRESULT FOR SELECT DISTINCT CO_DEPARTAMENTO AS CO_UBIGEO, 
        NO_DEPARTAMENTO AS DE_UBIGEO
        FROM  IDORRCC.GEVW_UBIGEOS 
        WHERE CO_CONTINENTE = '92' AND CO_PAIS = '33' AND ES_UBIGEO = '1' 
        AND ESTADO = 'ACTIVO'  AND TRIM(NO_DEPARTAMENTO) IS NOT NULL
        AND CO_DEPARTAMENTO > 0 AND CO_DEPARTAMENTO < 30
        ORDER BY 2;  

    ELSIF VCOD_LEN = 2 THEN 
        
        VCOD_DEP := SUBSTR(P_VCOD_UBIGEO,1,2);
        
        OPEN P_CRRESULT FOR SELECT DISTINCT CO_PROVINCIA AS CO_UBIGEO, 
        NO_PROVINCIA  AS DE_UBIGEO
        FROM  IDORRCC.GEVW_UBIGEOS 
        WHERE CO_CONTINENTE = '92' AND CO_PAIS = '33' AND ES_UBIGEO = '1' 
        AND ESTADO = 'ACTIVO'
        AND CO_PROVINCIA NOT IN ('00') AND CO_DEPARTAMENTO = VCOD_DEP
        ORDER BY 2;

    ELSIF VCOD_LEN = 4 THEN 

        VCOD_DEP := SUBSTR(P_VCOD_UBIGEO,1,2);
        VCOD_PRO := SUBSTR(P_VCOD_UBIGEO,3,2);
        
        OPEN P_CRRESULT FOR SELECT DISTINCT CO_DISTRITO AS CO_UBIGEO, 
        NO_DISTRITO  AS DE_UBIGEO
        FROM  IDORRCC.GEVW_UBIGEOS 
        WHERE CO_CONTINENTE = '92' AND CO_PAIS = '33' AND ES_UBIGEO = '1' AND ESTADO = 'ACTIVO'
        AND CO_DISTRITO NOT IN ('00') AND CO_DEPARTAMENTO = VCOD_DEP AND CO_PROVINCIA = VCOD_PRO
        ORDER BY 2;

    ELSIF VCOD_LEN = 6 THEN 

        VCOD_DEP := SUBSTR(P_VCOD_UBIGEO,1,2);
        VCOD_PRO := SUBSTR(P_VCOD_UBIGEO,3,2);
        VCOD_DIST := SUBSTR(P_VCOD_UBIGEO,5,2);
        
        OPEN P_CRRESULT FOR SELECT DISTINCT CO_CENTRO_POBLADO_O AS CO_UBIGEO,
        DE_CENTRO_POBLADO  AS DE_UBIGEO
        FROM  IDORRCC.GEVW_UBIGEOS 
        WHERE CO_CONTINENTE = '92' AND CO_PAIS = '33' AND ES_UBIGEO = '1' AND ESTADO = 'ACTIVO'
        AND CO_CENTRO_POBLADO NOT IN ('00') AND CO_DEPARTAMENTO = VCOD_DEP AND CO_PROVINCIA = VCOD_PRO
        AND CO_DISTRITO = VCOD_DIST
        ORDER BY 2;

    END IF;

END;