create or replace PROCEDURE EDSP_DET_SOL_LIBRO_OBTENER (
P_VID_SOL VARCHAR2,
P_CRRESULT OUT SYS_REFCURSOR
)
AS

BEGIN
    OPEN P_CRRESULT FOR
    SELECT ID_DET_SOL_LIBRO,
    ID_SOLICITUD,
    LIB.CO_ARTICULO,
    LIB.CO_LENGUA,
    NU_NUM_ULTIMA_ACTA,
    NU_CANTIDAD,
    CO_ESTADO, 
    ART.DE_ARTICULO, 
    LNG.DE_LENGUA
    FROM IDO_PLATAFORMA_EXPE.EDTD_DET_SOL_LIBRO LIB 
    INNER JOIN IDORRCC.RCTR_ARTICULO ART ON LIB.CO_ARTICULO = ART.CO_ARTICULO
    INNER JOIN IDORRCC.RCTR_LENGUA LNG ON LIB.CO_LENGUA = LNG.CO_LENGUA
    WHERE LIB.CO_ESTADO = '1' AND LIB.ID_SOLICITUD = P_VID_SOL;

END;