create or replace PROCEDURE EDSP_DET_RC_ULTIMO_X_DNI (
P_VDNI VARCHAR2,
P_CRRESULT OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CRRESULT FOR
    SELECT * FROM (
    SELECT ID_REGISTRO ,
    ID_TIPO_SOLICITUD_FIRMA,
    CO_TIPO_DOC_IDENTIDAD,
    NU_DOC_IDENTIDAD,
    AP_PRIMER_APELLIDO,
    AP_SEGUNDO_APELLIDO,
    NO_PRENOMBRES,   
    CO_OREC_REG_CIVIL,
    DE_DETALLE_OREC_CORTA,
    CO_ESTADO_REGISTRADOR,
    NU_CELULAR,
    DE_MAIL,
    FE_FECHA_ALTA,
    FE_FECHA_BAJA,
    FE_FECHA_ACTUALIZACION,
    CO_CONDICION,
    CO_MOTIVO_ACTUALIZA,
    CO_ESTADO_FORMATO,
	CO_CARGO_REGISTRADOR,
    DE_OBSERVACION,
    ID_DET_SOL_FIRMA
    FROM IDO_PLATAFORMA_EXPE.EDTC_REG_CIVIL
    WHERE NU_DOC_IDENTIDAD = P_VDNI
    ORDER BY ID_REGISTRO DESC
    )T WHERE ROWNUM = 1;
END;