create or replace PROCEDURE EDSP_EXP_LISTAR_POR_OFICINA
(   
    P_CCO_DEP CHAR,
    P_CCO_PROV CHAR,
    P_CCO_DIST CHAR,    
    P_CCO_OREC CHAR,   
    P_NPAGE NUMBER,
    P_NSIZE NUMBER,
    P_CRESULT OUT SYS_REFCURSOR,
    P_CRTOTAL OUT SYS_REFCURSOR 
)
AS
 SQL_SELECT_COUNT VARCHAR2(8000) := 'SELECT COUNT(1) TOTAL   
    FROM IDO_PLATAFORMA_EXPE.EDTM_REG_CIVIL RCV   
    INNER JOIN IDORRCC.RCVM_OREC ORE ON ORE.CO_OREC = RCV.CO_OREC_REG_CIVIL
    WHERE RCV.CO_ESTADO_REGISTRADOR = ''1'' ';

 SQL_QUERY VARCHAR2(8000) := 'SELECT 
    ROW_NUMBER() OVER(ORDER BY RCV.AP_PRIMER_APELLIDO,RCV.AP_SEGUNDO_APELLIDO,RCV.NO_PRENOMBRES) ROW_ID, 
    RCV.NU_DOC_IDENTIDAD,  
    RCV.AP_PRIMER_APELLIDO,
    RCV.AP_SEGUNDO_APELLIDO,
    RCV.NO_PRENOMBRES,
    RCV.DE_DETALLE_OREC_CORTA,
    ORE.NO_DEPARTAMENTO,
    ORE.NO_PROVINCIA,
    ORE.NO_DISTRITO,
    ORE.DE_CENTRO_POBLADO,
    RCV.NU_CELULAR,
    RCV.DE_MAIL
    FROM IDO_PLATAFORMA_EXPE.EDTM_REG_CIVIL RCV   
    INNER JOIN IDORRCC.RCVM_OREC ORE ON ORE.CO_OREC = RCV.CO_OREC_REG_CIVIL 
    WHERE RCV.CO_ESTADO_REGISTRADOR = ''1''  ';

 SQL_WHERE VARCHAR2(8000) := '';   

BEGIN   

  IF (P_CCO_DEP IS NOT NULL) THEN
    SQL_WHERE := SQL_WHERE || ' AND ORE.CO_DEPARTAMENTO = ''' || TRIM(P_CCO_DEP) || '''';
  END IF;

  IF (P_CCO_PROV IS NOT NULL) THEN
    SQL_WHERE := SQL_WHERE || ' AND ORE.CO_PROVINCIA = ''' || TRIM(P_CCO_PROV) || '''';
  END IF;

  IF (P_CCO_DIST IS NOT NULL) THEN
    SQL_WHERE := SQL_WHERE || ' AND ORE.CO_DISTRITO = ''' || TRIM(P_CCO_DIST) || '''';
  END IF;

  IF (P_CCO_OREC IS NOT NULL) THEN
    SQL_WHERE := SQL_WHERE || ' AND RCV.CO_OREC_REG_CIVIL = ''' || TRIM(P_CCO_OREC) || '''';
  END IF; 

  SQL_QUERY := 'SELECT * FROM ( ' || SQL_QUERY || SQL_WHERE || ' )TB WHERE TB.ROW_ID > ' || P_NPAGE*P_NSIZE  || ' AND TB.ROW_ID <= ' || (P_NPAGE+1)*P_NSIZE || '';
  SQL_SELECT_COUNT := SQL_SELECT_COUNT || SQL_WHERE; 

  OPEN P_CRESULT FOR SQL_QUERY;   
  OPEN P_CRTOTAL FOR SQL_SELECT_COUNT;
END;